production:
  adapter: postgresql
  encoding: utf8
  database: canvas_production
  host: <%= ENV.fetch("CANVAS_DATABASE_HOST") %>
  username: <%= ENV.fetch("CANVAS_DATABASE_USER") %>
  password: <%= ENV.fetch("CANVAS_DATABASE_PASSWORD") %>
  timeout: 5000